local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = 'Telescope find files' })
vim.keymap.set('n', '<leader>gf', builtin.live_grep, { desc = 'Telescope live grep' })
vim.keymap.set('n', '<leader>bf', builtin.buffers, { desc = 'Telescope buffers' })
vim.keymap.set('n', '<leader>hf', builtin.help_tags, { desc = 'Telescope help tags' })
